Policy Refactor, Extender
flarum/core pull request #2056
Opened 2020-03-08 00:53 UTC by askvortsov1

Foundation for fixing #1832
Part of #1891

**Changes proposed in this pull request:**
- Ask that policies return ->allow, ->deny, ->forceAllow, ->forceDeny instead of true/false to increase flexibility
- Improve evaluation of whether a user has the ability to do something on an instance to avoid order-dependence.
- Rename getPermission (->checkAbility), scopeModelVisibility (->scopeQueryListener) methods, as well as the methods scopeModelVisibility calls (->scopeQuery, ->scopeQueryPerAbility), for purposes of clarify.
- Restructure old scopeModelVisibility calls down to only 2 methods
- Refactor how policies are registered by moving them into the User service provider, making an Extender more viable
- Removed the GroupServiceProvider as it no longer does anything
- Deprecate everything that's no longer used
- Add Policy extender

**Reviewers should focus on:**
- I don't like that the gate->before callback now requires us to app->make ALL the policies every time we want to check a permission. The same applies to the part where we listen to ScopeModelVisibility. Should I add a singleton that contains resolved instances of all policies?
- Are the new names what we want?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

2020-07-19 21:07 UTC, askvortsov1 commented
Not stale.

2020-11-03 10:47 UTC, SychO9 requested changes

2020-11-03 10:47 UTC, SychO9 commented on src/User/AbstractPolicy.php
>      {
If this is deprecated, why don't we just call `checkAbility` from here, instead of having duplicated blocks of code.

2020-11-03 10:47 UTC, SychO9 commented on src/User/AbstractPolicy.php
>      {
same here, why not just call `scopeQueryListener`

2020-11-03 10:47 UTC, SychO9 commented on src/User/UserServiceProvider.php
> +                $results[] = $this->app->make($policy)->checkAbility($actor, $ability, $model);
Before this refactor, when policies were listeners, they were resolved only once.

How about we resolve them all in an array before making the gate and then we use that array of all resolved policies inside.

2020-11-03 10:47 UTC, SychO9 commented on src/User/UserServiceProvider.php
> +            $events->listen(ScopeModelVisibility::class, [$this->app->make($policy), 'scopeQueryListener']);
same here, let's resolve all policies once in an array before making the gate and use that.

2020-11-22 06:00 UTC, closed without merging