Validator extender
flarum/core pull request #2102
Opened 2020-03-29 23:29 UTC by askvortsov1

**Fixes part of #1891**

**Changes proposed in this pull request:**
- Add Validator extender with configure method
- Add integration tests
- Deprecate Validating event

**Reviewers should focus on:**
I slightly deviated from the previously discussed spec on this one, as I think that having a configure method that runs the validator through a callable gives us and developers more flexibility than simply the ability to add rules. Similarly, there are extensions that depend on this type of capabilities.

Should there be a dedicated method to run the ruleset through a callable as well? I'm not sure if that is necessary (this PR supports that), but it might be a nice shortcut.

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).

2020-04-22 23:41 UTC, askvortsov1 commented
Now, for validator extender I've looked through the code, and it's a tad bit tricker. The most commonly used things that SHOULD be explicit on the API are:

```
->addRule($attribute, $rule)
->removeRule($attribute, $rule) // Rule supports wildcard pattern matching

// For the following 2, I propose this system so that we force extension devs to translate any custom error messages they want to add.
->addMessage($rule, $messageTranslationKey)
->removeMessage($rule, $messageTranslationKey)

->addExtension($rule, $extension)
```

These alone should cover more than 99.9% of use case; however, there are other public methods on the validator API that, theoretically speaking, should be supported. Do we want to keep the generic "configure" method as well, or support every single one of those methods, or just support some?

Also, there's cases like this: https://github.com/branchzero/flarum-ext-qqcaptcha/blob/b043e38792614425d83f6085209c0b7486c1e57f/src/Listener/AddValidatorRule.php that use settings in deciding validation rules/extenders, what should be done there?

2020-07-10 11:34 UTC, franzliedke commented
> Similarly, there are extensions that depend on this type of capabilities.

Could you provide a few examples / links? It's hard to think about this in the abstract.

2020-07-10 16:01 UTC, askvortsov1 commented
> Could you provide a few examples / links? It's hard to think about this in the abstract.
https://github.com/FriendsOfFlarum/doorman/blob/bb428bcc6aa2e2f30d91fbe7361d7e7e3c19249c/src/Listeners/AddValidatorRule.php
https://github.com/FriendsOfFlarum/recaptcha/blob/b9df60ff5604c61e621b479c88823855212564f0/src/Listeners/AddValidatorRule.php
https://github.com/clarkwinkelmann/flarum-ext-passwordless/blob/a772005219b4005c8a4105c50e3f137093c90918/src/Listeners/DontRequirePasswordOnSignUp.php

Really, the only/biggest question is what to do with validator extensions, as they will often require DI)

2020-10-09 13:54 UTC, askvortsov1 commented
Not stale

2020-10-24 06:12 UTC, clarkwinkelmann requested changes
The deprecation messages will need to be updated (beta13 => beta14)

Regarding the code of the test, I'm not sure whether we want to explain what it does or simplify it? I believe it's copied from one of my example and the reason it's so complex is to keep the additional password rules that might have been made by other extensions. I think having a comment reminding that would be useful for future readers.

Or we could also use a shorter code that blindly replaces the rules without regard for other extensions. This might be something legitimately used in the local `extend.php` when the list of extensions is well known. Something like: (untested)

```php
        $this->extend((new Extend\Validator(UserValidator::class))->configure(function ($validator) {
                $validator->setRules([
                    'password' => [
                        'required',
                        'min:8'
                    ]
                ] + $validator->getRules());
            }
        }));
```

I think it would still make sense to pass the Flarum validator object to the callback. It could be the second param instead of the first like it was with the event. Sometimes values are stored on that object, for example the user instance on `UserValidator`.

There's also the not-exactly-related-but-somewhat-close matter of #2398 where an event might or might not make sense (?)

2020-10-29 16:37 UTC, clarkwinkelmann approved these changes
I have not tested locally, but this looks good :+1: 

Should the tests cover calling a callback/class that takes a single argument? This is something that should work in PHP? One of the two (callback or class) could omit the second argument on purpose (with a comment explaining it's omitted)

2020-11-01 16:22 UTC, tankerkiller125 approved these changes

2020-11-01 16:31 UTC, merged