Add warnings to Mithril 2 BC layer
flarum/core pull request #2313
Opened 2020-09-25 16:44 UTC by askvortsov1

2020-09-25 16:45 UTC, datitisev requested changes
You need to add checks so that you don't have a warning on *every* use of those methods - because with the current changes you WILL crash the console.

The warnings should only appear once.

2020-09-25 17:16 UTC, askvortsov1 commented
That is a good point, although I suppose it would get the point across that an upgrade is needed :rofl:. I don't really see a good way of doing this outside of creating a global boolean flag for each of these warnings...

2020-09-25 17:17 UTC, datitisev commented
Not global. A `let` at the beginning of the file for each warning is completely fine.

2020-09-25 20:14 UTC, franzliedke approved these changes

2020-09-27 01:48 UTC, tankerkiller125 approved these changes

2020-09-27 02:12 UTC, merged