Refactor PostStream animations
flarum/core pull request #2364
Opened 2020-10-05 18:56 UTC by askvortsov1

Fixes #2348 

- If the fadeIn animation is specified on the PostStream class itself, any time we add/remove another animation, it will redo fadeIn. To avoid this, we move fadeIn into it's own css class, which is applied, and then immediately removed after the animation is completed to ensure it only runs once.
- The "fix" for flashItem (#2300) was actually broken, as it resulted in '.flash' never being removed, so we never went back to .PostStream's fadeIn. We adjust flashItem to ensure that '.flash' is removed. We also remove 'fadeIn' in case it hasn't yet been removed in oncreate.

2020-10-07 22:53 UTC, clarkwinkelmann requested changes

2020-10-07 22:53 UTC, clarkwinkelmann commented on js/src/forum/components/PostStream.js
> +        <div className="PostStream-item fadeIn" key="reply">
This class won't be removed though, no?

2020-10-07 22:53 UTC, clarkwinkelmann commented on js/src/forum/components/PostStream.js
> +        attrs.oncreate = (vnode) => setTimeout(() => $(vnode.dom).removeClass('fadeIn'), 500); // We give enough time for the animation to complete
Mithril-wise wouldn't it be better to insert the `fadeIn` class via jQuery here? Right now I think if an extension triggers a full redraw of the page, the `fadeIn` class would be re-added.

Something like

```
attrs.oncreate = (vnode) => {
    $(vnode.dom).addClass('fadeIn');
    setTimeout(() => $(vnode.dom).removeClass('fadeIn'), 500)
};
```

I'd suggest a comment that references the original duration being CSS. Something like "// Duration of the fadeIn CSS animation + 100ms so it has time to complete"

2020-10-07 23:39 UTC, clarkwinkelmann approved these changes
Looking good code-wise :+1:

2020-10-15 20:45 UTC, datitisev approved these changes
Tested locally, works well & I think it improves the animations as well.

2020-10-15 21:34 UTC, merged