PostStream: Fix minor load more issue
flarum/core pull request #2388
Opened 2020-10-13 15:11 UTC by w-4

When we scroll to a post that is already loaded, the load more button might show and not trigger. 
To replicate (in beta.14) go to the start of a long enough discussion and run `app.current.get('stream').goToIndex(19)`.

**Screenshot**
before the fix:
![Screenshot_316](https://user-images.githubusercontent.com/36057469/95879297-67109300-0da0-11eb-9bc8-bc7eab717868.png)

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

2020-10-13 17:31 UTC, askvortsov1 commented
When testing locally, `app.current.get('stream').goToIndex(19)` on a long discussion with these changes results in repeated scrolling to and from the scrolled post.

2020-10-14 01:16 UTC, w-4 commented
This is might be due to https://github.com/flarum/core/pull/2384. Let's merge that in first and check again.

2020-10-14 01:39 UTC, w-4 commented
We could later also check by running `app.current.get('stream').goToNumber(20)`.  But I'd also wait for https://github.com/flarum/core/pull/2378 to be merged. It removes the `m.route.set` call in DiscussionPage `postionChanged` that could lead to an additional `goToNumber` call.

2020-11-29 23:11 UTC, askvortsov1 requested changes
Tested it again, and it works correctly with `app.current.get('stream').goToIndex(19)` (yay!).

 The only nitpick I have is that I think `loadPostsIfNeeded` would be a better method name than `loadPostsWhenNeeded`

2020-12-12 05:34 UTC, w-4 commented
Tested it as well, and it works. Also fixed the `app.current.get('stream').goToIndex(20)`.

2020-12-12 20:35 UTC, askvortsov1 requested changes
The `goToIndex(20)` issue was already fixed in https://github.com/flarum/core/commit/09e2736cbcc267594b660beabbd001d9030f9880, so I don't think we should duplicate it here (especially since the PR is about another topic), but otherwise LGTM!

2020-12-12 20:35 UTC, askvortsov1 commented on js/src/forum/states/PostStreamState.js
> -    if (index >= this.visibleStart && index <= this.visibleEnd) {
This was already done in https://github.com/flarum/core/commit/09e2736cbcc267594b660beabbd001d9030f9880, so a rebase would be better than repeating this change

2021-01-13 22:45 UTC, askvortsov1 approved these changes
Tested locally, works as intended

2021-02-10 19:13 UTC, SychO9 approved these changes

2021-02-10 19:22 UTC, merged