fix the ui modal problem in the change email
flarum/core pull request #2467
Opened 2020-11-25 09:19 UTC by azibom

**Fixes #1892**

**Changes proposed in this pull request:**

I just add the "this.alert = null" when i get the success response in the "ChangeEmailModal" component, and now if you write your password correctly, you do not see the last error alert.

2020-11-25 20:58 UTC, askvortsov1 requested changes

2020-11-25 20:58 UTC, askvortsov1 commented on js/src/forum/components/ChangeEmailModal.js
> -      .then(() => (
Hmm, wouldn't it be simpler to do:

```
.then(() => {
    this.success = true;
    this.alert = null;
})
```

2020-11-25 22:15 UTC, azibom commented on js/src/forum/components/ChangeEmailModal.js
> -      .then(() => (
yes, you are right, I will fix it

2020-11-26 04:09 UTC, askvortsov1 requested changes

2020-11-26 04:09 UTC, askvortsov1 commented on js/src/forum/components/ChangeEmailModal.js
> +        this.alert = null;
This should be `this.alertAttrs = null`.

2020-11-26 22:07 UTC, askvortsov1 approved these changes

2020-11-26 22:39 UTC, tankerkiller125 approved these changes

2020-11-26 22:53 UTC, merged

2020-12-22 23:23 UTC, franzliedke commented
Random thought: should we remove the "old" error message at the *beginning* of the request already, to make it more obvious that a hypothetical new error is the result of the new request? The request can take any amount of time, so having the error still visible may confuse users. If I am not mistaken, that's a pattern I've often seen with client-side validation: remove errors when submitting, show them anew if they still appear.

:wave:

2021-01-05 00:38 UTC, askvortsov1 commented
I like that approach! Is that something you'd like to PR, or should I open a new issue for it?

:wave: