Pass callback wrapper parameters by reference
flarum/core pull request #2485
Opened 2020-12-04 17:22 UTC by SychO9

**Fixes https://github.com/flarum/core/pull/2451#pullrequestreview-545124663**

**Changes proposed in this pull request:**
Because invokable class objects are not directly called and instead it's the callback wrapper that calls these objects, it's currently not possible to receive arguments by reference on an invokable class.

To fix this we pass the arguments by reference by default when calling the object in the callback wrapper.

2020-12-04 20:01 UTC, askvortsov1 requested changes
I think we should add a unit (not integration) test class for ContainerUtil that checks that it works as expected with pass-by-value, pass-by-reference, and a mixture of such.

2020-12-04 22:54 UTC, SychO9 commented
hmm, the `wrapCallback` method does require the container, I guess creating a custom container class with a dummy implementation for the `make` method should be fine ?

2020-12-04 22:58 UTC, askvortsov1 commented
Hmm, could we use `mock` to create a container instance?

2020-12-04 23:16 UTC, SychO9 commented
I'm not familiar with Mockery, as far as I can tell that won't work, `make` always ends up returning null. I do not as of yet know how Mockery works to know if that's even possible.

2020-12-05 19:45 UTC, askvortsov1 approved these changes

2020-12-06 19:58 UTC, askvortsov1 commented
Because invokable class objects are not directly called and instead it's the callback wrapper that calls these objects, it's currently not possible to receive arguments by reference on an invokable class.

To fix this we pass the arguments by reference by default when calling the object in the callback wrapper.

2020-12-06 19:58 UTC, merged