Refactor AccountActivationMailer and SendConfirmationEmailController
flarum/core pull request #2493
Opened 2020-12-10 22:21 UTC by sl-kr

**Fixes #2193**

**Changes proposed in this pull request:**

Moves the common code between [SendConfirmationEmailController](https://github.com/flarum/core/blob/master/src/Api/Controller/SendConfirmationEmailController.php) and [AccountActivationMailer](https://github.com/flarum/core/blob/master/src/User/AccountActivationMailer.php) into a trait.

**Reviewers should focus on:**

I wasn't sure what to name the trait or where to put it, but because most of the code for the trait was taken from the AccountActivationMailer class I decided to name it the AccountActivationMailerTrait and keep it in the same directory. Also, I decoupled the generateToken and getEmailData functions because I think it will make more modular and maintainable even through it may make using the trait more verbose.

**Confirmed**

- [x] Backend changes: tests are green (run `composer test`).

2020-12-11 06:56 UTC, askvortsov1 requested changes

2020-12-11 06:56 UTC, askvortsov1 commented on src/User/AccountActivationMailerTrait.php
> +    protected function getEmailData(User $user, $email, EmailToken $token)
Doesn't look like the email is actually used here

2020-12-11 06:56 UTC, askvortsov1 commented on src/User/AccountActivationMailerTrait.php
> +    protected function generateToken(User $user, $email)
I'm leaning towards keeping it like this, with the email passed in separately to allow future flexibility if we decide to adopt multiple emails per user.

2020-12-12 20:37 UTC, askvortsov1 approved these changes
Looks good to me!

2021-01-04 23:19 UTC, askvortsov1 commented
A side effect of this would implement https://github.com/flarum/core/issues/2515, which still needs a bit more discussion before merging this.

2021-03-19 17:05 UTC, SychO9 approved these changes

2021-03-19 17:06 UTC, merged