proposal to add handling to extending flarum from extensions
flarum/core pull request #2740
Opened 2021-03-26 08:40 UTC by luceos

**Changes proposed in this pull request:**

Captures any errors throw when trying to extend flarum from an extension. Right now when an extender misbehaves we get errors like these:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Closure::extend() in /home/forge/nightly.flarum.site/nightly/vendor/flarum/core/src/Extension/Extension.php:137
Stack trace:
```

Which isn't really useful, the trace doesn't show what extension nor what extender is causing the issue.

**Reviewers should focus on:**

Please do a local test I haven't been able to do so.

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

2021-03-30 06:10 UTC, askvortsov1 requested changes

2021-03-30 06:10 UTC, askvortsov1 commented on src/Extension/Exception/ExtendingFailedException.php
> +        parent::__construct($extension->getTitle().' has an invalid extend.php: '.get_class($extender), null, $previous);
This message is a bit confusing. Maybe:

` has an invalid extend.php: error experienced when applying extender of type: `?

2021-03-30 06:10 UTC, askvortsov1 commented on src/Extension/Exception/ExtendingFailedExceptionHandler.php
> +class ExtendingFailedExceptionHandler
I am not sure this is necessary; when we enable an extension, it won't actually be applied until the next refresh. At that point, the error will happen as a boot error, so our error handler won't have an opportunity to intercept. And this isn't used by the logging system. I don't think we need to do anything beyond just throwing the extension.

2021-03-30 06:10 UTC, askvortsov1 commented on src/Extension/Exception/ExtendingFailedException.php
> +        parent::__construct($extension->getTitle().' has an invalid extend.php: '.get_class($extender), null, $previous);
Actually we might want to go a little further:

```
Experienced an error when booting extension: EXTENSION_TITLE
Error occured when applying an extender of type: EXTENDER_CLASS
```

2021-04-29 18:11 UTC, askvortsov1 approved these changes

2021-04-29 20:15 UTC, SychO9 approved these changes

2021-04-29 20:17 UTC, merged