Revision compiler revised
flarum/core pull request #2805
Opened 2021-04-22 11:29 UTC by luceos

**Changes proposed in this pull request:**

Moving from `<asset>-<revision>.<js|css>` to `<asset>.<js|css>?v=<revision>`. As a consequence we no longer need to delete the old file, browsers will automatically pick up that a new file was generated. 

Additional changes

- clean up the revision classes, adding more type hinting (compatible with php 7.3), removing unneeded phpdoc
- changed the cache differentiator for Less; previously it would use `time()` causing a recompile every time assets are compiled; but as all sources (string, file) offer their own differentiator and the less compiler only adds import dirs, I've used that as another differentiator. Let me clarify the impact:

For production sites there won't be any change, except that css is compiled less often.
For development environments where import dirs see changes this might be problematic, however this PR also takes this into consideration by allowing the `commit()` method of the recompiler to get an argument `$force (false)`  to force recompilation when in debug mode.

**Reviewers should focus on:**

Whether we want to modify the differentator for Less like this.

**Screenshot**

![image](https://user-images.githubusercontent.com/504687/115707171-beef0e80-a36e-11eb-9ca0-80a746cd03b4.png)

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2021-04-22 12:32 UTC, davwheat commented
I love this! :)

2021-04-22 16:04 UTC, askvortsov1 requested changes
Changes look good to me, including the differentiator changes. Local testing confirms that less is recompiled when changed as expected. Just a slight nitpick, `commit` assumes debug mode (because it's only called during debug mode). Can we explicitly state this expectation either in a comment, or by renaming to something? `forceCommit` maybe?

2021-04-22 16:04 UTC, askvortsov1 commented on src/Frontend/Content/Assets.php
>      private function commit(array $compilers)
Can we add a comment saying "This method only runs when in debug mode, so we force a recompilation"?

2021-04-22 17:34 UTC, luceos commented
If the method is named commit, it feels superfluous to name the variable forceCommit. That's a waste of screen width and only makes it unclear as I'd expect something else to be forceable too 🙈

2021-04-22 17:40 UTC, askvortsov1 commented
> If the method is named commit

I meant renaming the method in the `Assets` class to `forceCommit`

2021-04-29 18:35 UTC, askvortsov1 approved these changes

2021-04-29 20:40 UTC, SychO9 approved these changes

2021-04-29 20:49 UTC, merged