Revert "Fix intervention/image version to 2.5.0"
flarum/core pull request #2986
Opened 2021-07-22 15:35 UTC by SychO9

intervention/image have pushed a fix and release 2.6.1, so this is no longer necessary.

https://github.com/Intervention/image/commit/e2b8aebe3e5baf1e3db61a0f5227502313d74b29

2021-07-22 16:55 UTC, davwheat approved these changes

2021-07-22 16:56 UTC, davwheat requested changes
Shouldn't we force 2.6.1 or 2.5.x in our composer JSON then with something like...


```
"intervention/image": "^2.6.1 || 2.5.*",
```

2021-07-24 17:47 UTC, SychO9 commented
> Shouldn't we force 2.6.1 or 2.5.x in our composer JSON then with something like...

Not really, if composer picks up `2.6.x` as the wanted version, it'll directly pick `2.6.1`, latest patch

2021-07-24 17:56 UTC, davwheat commented
> Not really, if composer picks up 2.6.x as the wanted version, it'll directly pick 2.6.1, latest patch

I think it's better safe than sorry. The suggested version range allows for a broken version of `intervention/image`, which we want to avoid.

If another package required `2.6.0` for some reason, this would break the entire forum unnecessarily instead of composer telling us that it won't work.

If we can tell composer to not pick 2.6.0 under any circumstances, like we can, I think that's the better option.

2021-07-24 18:38 UTC, SychO9 commented on composer.json
> +        "intervention/image": "^2.5.0",
```suggestion
        "intervention/image": "^2.6.1 || 2.5.*",
```

2021-07-24 18:38 UTC, SychO9 commented
> If another package required it at 2.6.0 or 2.5.* || 2.6.0 for some reason 

That would be a pretty bad package :p, sure why not.

2021-07-24 23:37 UTC, davwheat approved these changes

2021-07-26 11:02 UTC, merged