[WIP] CSS Code Housekeeping
flarum/core pull request #3026
Opened 2021-08-15 10:06 UTC by SychO9

**Progresses #2600**

**Changes proposed in this pull request:**
General cleanup of certain bits of code, all safe and doesn't change anything.
* Removed dead code.
* Used CSS Variables in certain scopes to improve customizability.

**Reviewers should focus on:**
🤷🏼‍♂️ 

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.

2021-08-15 10:08 UTC, davwheat commented
I'm definitely in favour of this direction. We should also remove all our vendor mixins (`.transition()`, `.box-shadow()`) as part of this PR.

2021-08-15 10:10 UTC, SychO9 commented
> I'm definitely in favour of this direction. We should also remove all our vendor mixins (`.transition()`, `.box-shadow()`) as part of this PR.

Yes as part of this PR and not others if you see what I mean :P

2021-08-15 10:39 UTC, SychO9 commented
Actually, removing the mixins would break any extensions using them 🤔

I'll just remove their usage for now.

2021-08-15 11:25 UTC, davwheat requested changes
We might want to remove the usages of translate3d. We can use normal translate instead.

This was a hack to force a separate compositing layer which was GPU optimised, but modern browsers do this automatically if transform is animated in any way in CSS.

We should also remove the unneeded `~""` surrounding some of the property values.

Couldn't be modify the mixing to only create the unprefixed version of each of the properties? That way extensions using them don't break, but they don't have the vendor prefixes either.

2021-08-15 11:27 UTC, davwheat commented on less/common/Modal.less
> +    transform: scale(0.9);
```suggestion
    transform: scale(1);
```

2021-08-15 11:28 UTC, davwheat commented on less/common/Modal.less
> +  transition: 0.2s opacity;
For consistency

```suggestion
  transition: opacity 0.2s;
```

2021-08-15 11:29 UTC, davwheat commented on less/common/Navigation.less
> +    transform: rotate(0deg);
```suggestion
    transform: rotate(0);
```

2021-08-15 11:34 UTC, davwheat commented on less/common/Search.less
> +    transition: all 0.4s;
We should probably avoid `all`. It's not your doing, but I wouldn't be opposed to you changing it ;)

https://www.joshwcomeau.com/animation/css-transitions/

2021-08-15 11:38 UTC, davwheat requested changes
Sorry about the multiple reviews. My fat fingers kept pressing the wrong button on mobile.

2021-08-15 11:38 UTC, davwheat commented on less/forum/PostStream.less
> +  animation: blink 1s linear;
We can combine these two lines into one. Same goes for below.

2021-08-15 11:38 UTC, davwheat commented on less/forum/PostStream.less
>  @-webkit-keyframes pulsate {
We can remove the WebKit version of this.

2021-08-15 11:38 UTC, davwheat commented on less/forum/SignUpModal.less
> -.SignUpModal-welcome {
Was this meant to be deleted?

2021-08-15 15:15 UTC, SychO9 commented on less/common/Dropdown.less
> +    transition: transform ~" 0.3s, visibility 0s 0.3s";
```suggestion
    transition: transform 0.3s, visibility 0s 0.3s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/Dropdown.less
> +    transition: ~"opacity 0.3s";
```suggestion
    transition: opacity 0.3s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/FormControl.less
> +  transition: ~"border-color .15s, background .15s";
```suggestion
  transition: border-color .15s, background .15s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/Modal.less
> +  transition: 0.2s opacity;
```suggestion
  transition: opacity 0.2s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/Navigation.less
> +  transition: ~"opacity 0.2s, margin-left 0.2s";
```suggestion
  transition: opacity 0.2s, margin-left 0.2s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/Tooltip.less
> +  transition: 0.15s opacity linear;
```suggestion
  transition: opacity 0.15s linear;
```

2021-08-15 15:15 UTC, SychO9 commented on less/common/mixins/header-background.less
> +  transition: ~"box-shadow 0.2s, -webkit-transform 0.2s";
Not sure what the `-webkit-transform` here is for, there isn't even a transform property 🤔 but either way we can change that to `transform`.

```suggestion
  transition: box-shadow 0.2s, transform 0.2s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/forum/Composer.less
> +    transition: ~"background 0.2s, box-shadow 0.2s";
```suggestion
    transition: background 0.2s, box-shadow 0.2s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/forum/Composer.less
> +      box-shadow: ~"0 0 0 2px @{primary-color}, 0 2px 6px @{shadow-color}";
```suggestion
      box-shadow: 0 0 0 2px @primary-color, 0 2px 6px @shadow-color;
```

2021-08-15 15:15 UTC, SychO9 commented on less/forum/Post.less
> +    transition: ~"opacity 0.2s, transform 0.2s";
```suggestion
    transition: opacity 0.2s, transform 0.2s;
```

2021-08-15 15:15 UTC, SychO9 commented on less/forum/Slidable.less
> +      transition: ~"box-shadow 0.2s, border-radius 0.2s";
```suggestion
      transition: box-shadow 0.2s, border-radius 0.2s;
```

2021-08-20 13:43 UTC, SychO9 commented
> We might want to remove the usages of translate3d. We can use normal translate instead.
>
> This was a hack to force a separate compositing layer which was GPU optimised, but modern browsers do this automatically if transform is animated in any way in CSS.

I couldn't find anything online about this to make sure it's no longer necessary :/

> Couldn't be modify the mixing to only create the unprefixed version of each of the properties? That way extensions using them don't break, but they don't have the vendor prefixes either.

The deprecated mixins here are all vendor-less though, you removed them in a previous PR.

2021-08-21 17:44 UTC, SychO9 commented
This should be enough for now.

2021-08-21 18:10 UTC, davwheat approved these changes

2021-08-21 18:26 UTC, askvortsov1 approved these changes

2021-08-21 18:34 UTC, merged