Add typing files for our translator libraries
flarum/core pull request #3175
Opened 2021-11-22 01:54 UTC by askvortsov1

Title says it all.

2021-11-22 02:02 UTC, davwheat requested changes
Should this not go in our global types folder?

2021-11-22 02:31 UTC, askvortsov1 commented
> Should this not go in our global types folder?

No, as we don't export these libraries to be globally available

2021-11-25 22:23 UTC, SychO9 approved these changes

2021-11-26 06:44 UTC, davwheat approved these changes

2021-11-26 22:26 UTC, merged