`listItems` typing fix
flarum/core pull request #3176
Opened 2021-11-22 02:56 UTC by askvortsov1

Currently, `listItems` is causing issues because it does not accept all `Mithril.Children`. This PR refactors its internals and types to support any input adhering to `Mithril.Children`. It also cleans up some messy internal logic.

2021-11-23 21:15 UTC, davwheat requested changes

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +interface ModdedChildArray extends Array<ModdedChildren> {}
```suggestion
type ModdedChildArray = ModdedChildren[];
```

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +type ModdedChildrenWithItemname = ModdedChildren & { itemName?: string };
```suggestion
type ModdedChildrenWithItemName = ModdedChildren & { itemName?: string };
```

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +function withoutUnnecessarySeparators(items: ModdedChildrenWithItemname[]): ModdedChildrenWithItemname[] {
```suggestion
function withoutUnnecessarySeparators(items: ModdedChildrenWithItemName[]): ModdedChildrenWithItemName[] {
```

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +  const newItems: ModdedChildrenWithItemname[] = [];
```suggestion
  const newItems: ModdedChildrenWithItemName[] = [];
```

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +  rawItems: ModdedChildrenWithItemname[],
```suggestion
  rawItems: ModdedChildrenWithItemName[],
```

2021-11-23 21:15 UTC, davwheat commented on js/src/common/helpers/listItems.tsx
> +  customTag: string | (new () => Component<Attrs>) = 'li',
I'd prefer to use [this](https://github.com/flarum/core/pull/3140#discussion_r753850972) instead of the union type.

2021-11-23 22:43 UTC, datitisev commented on js/src/common/helpers/listItems.tsx
> +type ModdedChildrenWithItemName = ModdedChildren & { itemName?: string };
Why not export this? I understand not exporting most of these, but at least `ModdedVnode` and/or `ModdedChildrenWithItemName`?

2021-12-01 22:44 UTC, davwheat approved these changes

2021-12-12 19:45 UTC, SychO9 approved these changes

2021-12-12 19:51 UTC, merged