Finish typing, TypeScript checks enabled
flarum/core pull request #3196
Opened 2021-12-13 03:54 UTC by askvortsov1

Fix remaining type issues in our current subset of converted TS code, re-enable errors if typecheck GH action fails.

2021-12-13 21:19 UTC, SychO9 approved these changes

2021-12-14 00:39 UTC, davwheat requested changes

2021-12-14 00:39 UTC, davwheat commented on js/src/forum/components/ForgotPasswordModal.tsx
> +import RequestError from '../../common/utils/RequestError';
```suggestion
import type Mithril from 'mithril';
import type RequestError from '../../common/utils/RequestError';
```

2021-12-14 00:39 UTC, davwheat commented on js/src/forum/components/LogInModal.tsx
> +import RequestError from '../../common/utils/RequestError';
```suggestion
import type RequestError from '../../common/utils/RequestError';
```

2021-12-14 01:18 UTC, askvortsov1 commented on js/src/common/components/EditUserModal.tsx
> +    return user && (user.groups() || []).some((g) => g?.id() === Group.ADMINISTRATOR_ID);
That's not really accurate, see [Playground Link](https://www.typescriptlang.org/play?#code/C4TwDgpgBAKlC8UDeAoK6oEMBcUBiArgHYDGwAlgPZEDcKAvlAD5TEAmEAZuURG3ShLUAzsCgQAHuVHDccRKgxZcACgCUCAHxQA5Jh0MUgkWKKVgAUSky5CVkQ7debLMKxEQRoUWGUANhAAdH6UAOYqktLAwgD8gZjqasY+-kEh4WaW1tFxCWpqQA)

It's not that `x.a` might or may not be defined, but that `x` itself might or might not be defined.

2021-12-14 01:27 UTC, davwheat commented on js/src/common/components/EditUserModal.tsx
> +    return user && (user.groups() || []).some((g) => g?.id() === Group.ADMINISTRATOR_ID);
Gotcha!

2021-12-14 01:33 UTC, davwheat approved these changes
Sorry, I missed some more type import suggestions last time.

After this, it's good to merge imo, but I'll probably be asleep when you do it.

2021-12-14 01:33 UTC, davwheat commented on js/src/admin/components/ReadmeModal.tsx
> +import { Extension } from '../AdminApplication';
```suggestion
import type { Extension } from '../AdminApplication';
```

2021-12-14 01:33 UTC, davwheat commented on js/src/common/components/EditUserModal.tsx
> +import { SaveAttributes, SaveRelationships } from '../Model';
```suggestion
import type { SaveAttributes, SaveRelationships } from '../Model';
```

2021-12-14 01:33 UTC, davwheat commented on js/src/common/components/RequestErrorModal.tsx
> +import RequestError from '../utils/RequestError';
```suggestion
import type RequestError from '../utils/RequestError';
```

2021-12-14 01:33 UTC, davwheat commented on js/src/common/states/ModalManagerState.ts
> +import Component from '../Component';
```suggestion
import type Component from '../Component';
```

2021-12-14 01:33 UTC, davwheat commented on js/src/forum/components/ForgotPasswordModal.tsx
> +import RequestError from '../../common/utils/RequestError';
This one seems to have not been done.

2021-12-14 01:33 UTC, davwheat commented on js/src/forum/components/LogInModal.tsx
> +import RequestError from '../../common/utils/RequestError';
Nor this

2021-12-14 03:07 UTC, merged