Kom/update-readme-file Fix broken contribution link at readme file
flarum/core pull request #3211
Opened 2021-12-16 20:33 UTC by komandar

Fix broken contribution link at core readme.md. Also migrate the readme.md info from flarum readme to the core one.

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2021-12-16 21:23 UTC, davwheat requested changes

2021-12-16 21:23 UTC, davwheat commented on README.md
> +This repository contains Flarum's core code. If you want to set up a forum, visit the [Flarum skeleton repository](https://github.com/flarum/flarum).  For support, refer to the [documentation](https:
```suggestion
This repository contains Flarum's core code. If you want to set up a forum, visit the [Flarum skeleton repository](https://github.com/flarum/flarum). For support, refer to the [documentation](https://docs.flarum.org/), and ask questions on the [Flarum Discuss](https://discuss.flarum.org/) (our community forum) or [Discord server](https://flarum.org/discord/).
```

2021-12-16 21:23 UTC, davwheat commented on README.md
> +![screenshot](https://flarum.org/assets/img/home-screenshot.png)
```suggestion
![Screenshot of a Flarum instance, showing multiple discussions and tags.](https://flarum.org/assets/img/home-screenshot.png)
```

2021-12-16 21:32 UTC, komandar commented on README.md
> +![screenshot](https://flarum.org/assets/img/home-screenshot.png)
Looks good for me :+1:

2021-12-16 21:32 UTC, komandar commented on README.md
> +This repository contains Flarum's core code. If you want to set up a forum, visit the [Flarum skeleton repository](https://github.com/flarum/flarum).  For support, refer to the [documentation](https:
Looks good for me :+1:

2021-12-17 01:32 UTC, davwheat commented on README.md
> +This repository contains Flarum's core code. If you want to set up a forum, visit the [Flarum skeleton repository](https://github.com/flarum/flarum). For support, refer to the [documentation](https:/
Sorry, I made a typo here 🙈 

```suggestion
This repository contains Flarum's core code. If you want to set up a forum, visit the [Flarum skeleton repository](https://github.com/flarum/flarum). For support, refer to the [documentation](https://docs.flarum.org/), and ask questions on [Flarum Discuss](https://discuss.flarum.org/) (our community forum) or [Discord server](https://flarum.org/discord/).
```

2021-12-20 00:49 UTC, davwheat approved these changes

2021-12-20 19:54 UTC, askvortsov1 approved these changes

2021-12-20 19:55 UTC, merged