chore: update FontAwesome v6 icon search link
flarum/core pull request #4036
Opened 2024-09-28 16:16 UTC by datlechin

**Fixes #0000**

**Changes proposed in this pull request:**

**Reviewers should focus on:**

**Screenshot**

**QA**

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2024-09-28 16:33 UTC, SychO9 requested changes
Could you please do the same for any other fonteawesome links? like the ones in tags for example, there might be others.

I would suggest creating a new property in the common/Application class, maybe named `refs`.

and then we could use that (`app.refs.fontawesome`) every time we need to link to fontawesome search.

Also please use `https://fontawesome.com/v6/icons?o=r&m=free`

2024-09-28 17:04 UTC, datlechin commented
@SychO9, I have added a new property in the common Application, following your suggestion, to reuse `app.refs.fontawesome`. Please let me know if any changes are needed

2024-09-28 17:54 UTC, SychO9 requested changes

2024-09-28 17:54 UTC, SychO9 commented on framework/core/js/src/common/Application.tsx
> +  refs: Record<string, unknown> = {};
Let's directly add the value here instead of calling a function. The function isn't necessary at this time 👍

2024-09-28 18:34 UTC, SychO9 commented on framework/core/js/src/common/Application.tsx
> +  refs: Record<string, unknown> = {
I think we can probably always expect the values to be strings for this one 🤔 

```suggestion
  refs: Record<string, string> = {
```

2024-09-29 08:14 UTC, SychO9 approved these changes
Thanks!

2024-09-29 08:14 UTC, merged

2025-03-16 12:47 UTC, thatdh commented
Seems `/icons?o=r&m=free` is broken (redirects to all icons)

main `https://fontawesome.com/v5/search?ic=free`
2.x `https://fontawesome.com/v6/search?ic=free`