Implement Support for Translatable Validation Attribute Errors
flarum/core pull request #4070
Opened 2024-10-12 18:32 UTC by DavideIadeluca

**Fixes #0000**
> [!NOTE]
> This PR aims to implement the translation of attributes of validation errors, a feature initially started nearly a decade ago (see [this commit](https://github.com/flarum/lang-english/commit/9282a13482952917f37a90606fcd7647e554fd70#diff-5766ba3bdb01276b2dea1519c80516dd3c94e8ebd39ecb88ccde0897cbd537f5R61-R69)) but seemingly never completed. 

**Changes proposed in this pull request:**
- Implement support for translating **attributes** of backend validation errors. 
- Add English translations for new attributes
- Move tag validation attribute translations from `core` to `tags` per discussion in https://github.com/flarum/framework/pull/2408#discussion_r560572646

**Reviewers should focus on:**
- First and foremost, evaluate if this change is not a breaking change and can safely be done on `1.x`. The only concern with my implementation is that some extensions may have already defined a key in the `validation` namespace, like `validation.attributes.name`, which could lead to unexpected behavior. In any case, I recommend reading the discussion in https://github.com/flarum/framework/pull/2408#discussion_r560572646 to get more context on this.
- Would there be a way how the same could be achieved without having to explicitly return a translation key for each attribute? Let's say there was some kind of generic solution, how would we handle cases such as this: https://github.com/flarum/framework/blob/5bd7e5dfe3d55d8252bd27dd01915e9be6453724/extensions/package-manager/src/ConfigureComposerValidator.php#L18-L24

- Should a similar solution be PR'd for `2.x` or are you looking for something more lean perhaps without the risk of a breaking change?

**Screenshot**

**QA**

1. Install a language pack such as `flarum-lang/german` or `flarum-lang/dutch`
2. Switch the Forum UI to another language (not english)
3. Try to submit a new discussions with no title or content. You should now see the translated version of `title` or `content`

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

2024-10-12 19:03 UTC, SychO9 commented
It should be possible to edit AbstractValidator and manipulate the messages to dynamically check for the existence of a validation attribute translation. Mainly, the result of `getMessages`.

2024-10-12 19:15 UTC, SychO9 commented
The only concern is potential conflicts in attribute names between extensions. So might be better to put extension validation under the extension namespace.

2024-10-17 11:25 UTC, imorland requested changes
As @SychO9 suggests, we run the possibility of conflicts here if extensions register the same attribute names, but want a different translation.

Let's scope everything under the extension name(s) please

2024-10-19 17:51 UTC, DavideIadeluca commented
@imorland I moved the validation translations to the extension namespaces

> It should be possible to edit AbstractValidator and manipulate the messages to dynamically check for the existence of a validation attribute translation. Mainly, the result of `getMessages`.

@SychO9 Can you make an example of what you were thinking? Now that some validation strings are in the extension namespaces, I feel like it would get messy if the `AbstractValidator` has to support both the structure of core and extensions but maybe I'm missing something here

2024-10-19 19:26 UTC, SychO9 commented
here is a proof of concept of how you can obtain the extension ID related to the validator:

```php
// this would be nice in a trait, used by the abstract validator in this case
protected function getClassExtensionId(): ?string
{
    $extensions = resolve(ExtensionManager::class);

    return $extensions->getExtensions()
                ->mapWithKeys(function (\Flarum\Extension\Extension $extension) {
                    return [$extension->getId() => $extension->getNamespace()];
                })
                ->where(function ($namespace) use ($class) {
                    return $namespace && str_starts_with(static::class, $namespace);
                })
                ->keys()
                ->first();
}
```

you would have to add this to `Extension.php`

```php
    public function getNamespace(): ?string
    {
        return Collection::make($this->composerJsonAttribute('autoload.psr-4'))
            ->filter(function ($source) {
                return $source === 'src/';
            })
            ->keys()
            ->first();
    }
```

once you have that, you could theoretically use it in the getMessages method to automatically point to `$extId.validation.attributes.$attribute` or `validation.attributes.$attribute` if core (extId null)

also imo it's not necessary to replace `.` with `_` for attribute locale key.

2024-11-09 11:23 UTC, imorland commented
I'll tentatively add this to the `1.8.9` milestone, if you have the chance to complete it before the due date, then I'm happy to include it in that release @DavideIadeluca

2024-11-14 15:14 UTC, DavideIadeluca commented
@imorland I've now refactored the implementation per Samis suggestion. One case that is now knowingly missing here is the validation logic in `SaveTagsToDatabase`. The `SaveTagsToDatabase` creates it's own validator, which then doesn't use the new logic.

https://github.com/flarum/framework/blob/8eb56b16cf5670622da41fb00abfca2fdc1f6328/extensions/tags/src/Listener/SaveTagsToDatabase.php#L131-L145

There are two other examples where a new validator is created instead of the `AbstractValidator` extended:

- `SettingsValidator`
- `RegisterUserHandler`

Should refactoring of the validation logic be done in this PR or separately (or not at all)? 

Also, would it make sense to add tests for this?

2024-11-19 17:16 UTC, imorland commented
I'll never say no to tests! But yeah, at least a couple of tests to validate the changes would be nice, if possible.

Regarding the 3 other validators, I think it would be nice to have `RegisterUserHandler` using the new logic, as that's user facing (mostly). The other 2 I would say are optional. If you have the time, then this could be a seperate PR

2024-11-20 08:50 UTC, imorland approved these changes

2024-11-20 08:51 UTC, merged