fix: Ignore isLiked when post is not comment post.
flarum/core pull request #4075
Opened 2024-10-17 17:02 UTC by zxy19

**Changes proposed in this pull request:**

When someone set `isLiked` attribute on a post that's not a `comment` (e.g. type `discussionTagged`) through api, it will be saved and send the notification to user. Then in `PostLikedNotification` component, the method `excerpt` is trying to get the `plainContent` to truncate, which will lead to a frontend error.

According to `addLikeAction.js`, user should only be able to like a comment post, so it should be ignore if target post is not a comment post.

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

2024-10-17 17:15 UTC, YUCLing commented
In that case, you'll be better off detaching all the likes from the posts. Since the like and unlike are both forbidden now, there's no way to achieve it except by modifying the database.

2024-10-17 18:00 UTC, zxy19 commented
> In that case, you'll be better off detaching all the likes from the posts. Since the like and unlike are both forbidden now, there's no way to achieve it except by modifying the database.

You are right. A new migration file was add to remove those records.

2024-10-17 23:09 UTC, YUCLing commented
Hang on... I think this fix will reduce the extensibility of the Likes extension. Another way of fixing this is preferred. 🤔

2024-10-18 03:07 UTC, ExerciseBook requested changes

2024-10-18 03:07 UTC, ExerciseBook commented on extensions/likes/src/Listener/SaveLikesToDatabase.php
> +        if ($post->exists && isset($data['attributes']['isLiked']) && $post->type === 'comment') {
I think this is not a common usage.

If we do want to LIKE a main discussion?

2024-10-18 03:07 UTC, ExerciseBook commented on extensions/likes/migrations/2024_10_18_000000_detach_likes_from_non_comment_posts.php
> +            ->delete();
is it no need to delete?

just keep it in database for rolling back.

2024-10-18 03:10 UTC, ExerciseBook commented
If you do consider it as a big due, just filter this logic in client side.

Keep connection IDL simple and do things on client side maybe a better choice.

2024-10-18 03:13 UTC, ExerciseBook requested changes

2024-10-18 03:13 UTC, ExerciseBook commented on extensions/likes/src/Listener/SaveLikesToDatabase.php
> +        if ($post->exists && isset($data['attributes']['isLiked']) && $post->type === 'comment') {
What we can do if we do want to LIKE a main discussion?

2024-10-18 03:13 UTC, ExerciseBook commented on extensions/likes/src/Listener/SaveLikesToDatabase.php
adding it in `$actor->assertCan('like', $post);` may be better?

2024-11-13 08:34 UTC, luceos commented
So the issue here is:

Liking any other Post type than CommentPost is causing issues with notifications.

The PR #4095 relates to this exact issue as well. Reference: https://github.com/flarum/framework/pull/4095#discussion_r1839725082

What I think should happen is create an extensible layer by adding a property to the implementation of every `Post` type, eg `CommentPost` that indicates whether notifications should be sent.

I'm closing this PR and the other one and will create an issue to explain further.

PS deleting all previous likes to start with a clean slate will not be appreciated by our users.

2024-11-13 08:34 UTC, closed without merging